# Generated by Django 4.0.3 on 2022-04-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='person.person'),
        ),
    ]
